---
title: "Hong Kong Shanghai and Shenzhen"
author: "Chen Jheng-Yi"
date: "2018/4/13"
output: ioslides_presentation
---


```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(tidyverse); library(lubridate); library(magrittr); library(stringr)
library(ggplot2); library(dygraphs); library(highcharter); library(plotly)
library(zoo); library(xts)
library(quantmod); library(Quandl); library(tidyquant); library(quantstrat)
library(egcm); library(PairTrading); library(PerformanceAnalytics); library(TTR)
library(FinancialInstrument); library(blotter); require(IKTrading)
```




## Shanghai and Hong Kong
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
ggplot() + 
  geom_bar(data = Shanghai_Shenzhen_to_Hong_Kong, aes(x = Date,y = from.Shanghai), stat = "identity")
```




## Shanghai and Hong Kong
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
Shanghai_Hong_Kong <- ggplot(Shanghai_Shenzhen_Hong_Kong, aes(x = Date, y = Hang.Seng.Index)) +
  geom_line(aes(x = Date, y = Hang.Seng.Index)) + 
  # geom_line(aes(x = Date, y = from.Shanghai)) +
  geom_bar(data = Shanghai_Shenzhen_Hong_Kong, aes(x = Date,y = from.Shanghai), stat = "identity")
Shanghai_Hong_Kong
# ggplotly(Shanghai_Hong_Kong)
```




















## Shanghai and Hong Kong
```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
Shanghai_Shenzhen_Hong_Kong <- xts(x = Shanghai_Shenzhen_Hong_Kong, order.by = Shanghai_Shenzhen_Hong_Kong$Date)
Shanghai_Shenzhen_Hong_Kong <- Shanghai_Shenzhen_Hong_Kong[, -3]

```

```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
dygraph(Shanghai_Shenzhen_Hong_Kong["/2016-12-05"]) %>% 
  dySeries("from.Shanghai", axis = "y2") %>% 
  dyRangeSelector(height = 10)
```















## Shenzhen and Hong Kong
```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
Shanghai_Shenzhen_to_Hong_Kong <- xts(x = Shanghai_Shenzhen_to_Hong_Kong, order.by = Shanghai_Shenzhen_to_Hong_Kong$Date)
Shanghai_Shenzhen_to_Hong_Kong <- Shanghai_Shenzhen_to_Hong_Kong[, -2] %>% na.omit()
```


```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
dygraph(Shanghai_Shenzhen_to_Hong_Kong) %>% 
  dySeries("from.Shenzhen", axis = "y2") %>% 
  dyRangeSelector(height = 10)
```








```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
Shanghai_to_Hong_Kong <- read.csv("F:/Data/Shanghai_to_Hong_Kong.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
Shanghai_to_Hong_Kong <- Shanghai_to_Hong_Kong[, c(1, 2, 10)]
names(Shanghai_to_Hong_Kong) <- c("Date", "Net.Inflow.of.Funds.per.Day.from.Shanghai", "Hang.Seng.Index")
names(Shanghai_to_Hong_Kong) <- c("Date", "from.Shanghai", "Hang.Seng.Index")

Shenzhen_to_Hong_Kong <- read.csv("F:/Data/Shenzhen_to_Hong_Kong.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
Shenzhen_to_Hong_Kong <- Shenzhen_to_Hong_Kong[, c(1, 2, 10)]
names(Shenzhen_to_Hong_Kong) <- c("Date", "Net.Inflow.of.Funds.per.Day.from.Shenzhen", "Hang.Seng.Index")
names(Shenzhen_to_Hong_Kong) <- c("Date", "from.Shenzhen", "Hang.Seng.Index")

Shanghai_Shenzhen_to_Hong_Kong <- left_join(Shanghai_to_Hong_Kong, Shenzhen_to_Hong_Kong, by = "Date")

Shanghai_Shenzhen_to_Hong_Kong$Hang.Seng.Index <- Shanghai_Shenzhen_to_Hong_Kong$Hang.Seng.Index.x
Shanghai_Shenzhen_to_Hong_Kong <- Shanghai_Shenzhen_to_Hong_Kong %>% select(-Hang.Seng.Index.y, -Hang.Seng.Index.x)
Shanghai_Shenzhen_to_Hong_Kong <- Shanghai_Shenzhen_to_Hong_Kong %>% filter(Hang.Seng.Index != "-")
Shanghai_Shenzhen_to_Hong_Kong$Hang.Seng.Index <- as.numeric(Shanghai_Shenzhen_to_Hong_Kong$Hang.Seng.Index)
Shanghai_Shenzhen_to_Hong_Kong$Date <- as.Date(Shanghai_Shenzhen_to_Hong_Kong$Date)
Shanghai_Shenzhen_to_Hong_Kong$from.Shanghai <- Shanghai_Shenzhen_to_Hong_Kong$from.Shanghai*100
Shanghai_Shenzhen_to_Hong_Kong$from.Shenzhen <- Shanghai_Shenzhen_to_Hong_Kong$from.Shenzhen*100
Shanghai_Shenzhen_to_Hong_Kong$from.Shanghai.Shenzhen <- Shanghai_Shenzhen_to_Hong_Kong$from.Shanghai %>% na.omit() + Shanghai_Shenzhen_to_Hong_Kong$from.Shenzhen %>% na.omit()
# glimpse(Shanghai_Shenzhen_to_Hong_Kong)
```



## Shanghai, Shenzhen and Hong Kong
```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
Shanghai_Shenzhen_to_Hong_Kong <- xts(x = Shanghai_Shenzhen_to_Hong_Kong, order.by = Shanghai_Shenzhen_to_Hong_Kong$Date)
Shanghai_Shenzhen_to_Hong_Kong <- Shanghai_Shenzhen_to_Hong_Kong[, -c(2, 3)] %>% na.omit()

```



```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
dygraph(Shanghai_Shenzhen_to_Hong_Kong) %>% 
  dySeries("from.Shanghai.Shenzhen", axis = "y2") %>% 
  dyRangeSelector(height = 10) %>% 
  dyHighlight(highlightCircleSize = 3, highlightSeriesBackgroundAlpha = 0.2, hideOnMouseOut = FALSE)
  # dyLegend(show = "follow")
```


